version: 0.2

phases:
  build:
    commands:
      - echo Build started
  post_build:
    commands:
      - echo Deploying to EC2 via SSM
      - aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=InstanceIds,Values=$INSTANCE_ID" --parameters '{"commands":["cd /home/ec2-user/babystore-app || git clone https://github.com/Yusuf-Karanib/babystore-app.git /home/ec2-user/babystore-app", "cd /home/ec2-user/babystore-app", "git pull origin master", "sudo bash start.sh"]}' --region us-east-1